import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import { BlogsProvider } from "@/context/blogsContext";
import { ItemsProvider } from "@/context/itemsContext";

const myFont = localFont({
  src: './fonts/Lexend.ttf',
  variable: '--lexend',
})

export const metadata: Metadata = {
  title: "Orion Farms",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFont.variable} antialiased`}
      >
        <BlogsProvider>
          <ItemsProvider>
            <Header/>
            {children}
            <Footer/>
          </ItemsProvider>
        </BlogsProvider>
      </body>
    </html>
  );
}
